[package]
name = "flappy_dragon"
version = "0.1.0"
authors = ["Richard Lewis <richard@rjlewis.me.uk>"]
edition = "2018"

[dependencies]
array2d = "0.2.1"
itertools = "0.10.5"
rand = "0.8.5"
sdl2 = "0.35.2"
